name: Custom issue template 
description: Please use this template for all other issues or concerns
assignees: kdumschott
body:
  - type: checkboxes
    id: Typeofissue
    attributes:
      label: Type of Issue
      description: "Please check if this issue involves the following:"
      options:
        - label: "Report a Bug"
        - label: "Report a Typo or Error"
        - label: "Feature Request"
        - label: "Help or Question"
        
  - type: textarea
    id: describe
    attributes:
      label: Comments
      description: Please describe the issue concern in as much detail as possible and provide as many links or references as needed to clearly explain the situation. 
    validations:
      required: true
